export const enumCode = new Map<number, string>()
    enumCode.set(1, 'ROLES')
    enumCode.set(2, 'USERS')
    enumCode.set(3, 'COMP')
    enumCode.set(4, 'EMP')
    enumCode.set(5, 'LOCTN')
    enumCode.set(6, 'PERMSN')
    enumCode.set(7, 'INVC')
    enumCode.set(8, 'ITMTYPES')
    enumCode.set(9, 'ITEMS')
    enumCode.set(10, 'ITMBRANDS')
    enumCode.set(11, 'ASSETS')
    enumCode.set(12, 'LMSIN')
    enumCode.set(13, 'LMSOUT')
    
